server:
  contextPath:
  port: 8080
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
        host: localhost:8080
api:
  basePackage: no.nc
spring:
  application:
    name: @project.artifactId@
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
