server:
  contextPath:
  port: 8080
swagger-ui:
  version: @swagger-ui.version@
spring:
  application:
    name: @project.artifactId@
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
