swagger: "2.0"
info:
  title: Swagger first demonstration
  version: '1.0'
  description: An API demonstrating a Swagger first approach to API-development.
host: localhost:8080
basePath: /
schemes:
  - http
paths:
  /ping:
    get:
      description: Accepts an optional message and returns it with a timestamp.
      produces:
        - application/json
      parameters:
        - name: message
          description: The message.
          type: string
          in: query
          required: false
      tags:
        - Ping
      operationId: ping
      responses:
        '200':
          description: Everything's fine.
          schema:
            $ref: '#/definitions/Pong'
definitions:
  Pong:
    type: object
    description: A message and a timestamp.
    properties:
      message:
        type: string
      dateAndTime:
        type: string
        format: date-time