openapi: "3.0.0"
info:
  title: Swagger first demonstration
  version: '1.0'
  description: An API demonstrating a Swagger first approach to API-development.
paths:
  /ping:
    get:
      description: Accepts an optional message and returns it with a timestamp.
      parameters:
        - name: message
          description: The message.
          in: query
          required: false
          schema:
            type: string
      tags:
        - Ping
      operationId: ping
      responses:
        '200':
          description: Everything's fine.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pong'
components:
  schemas:
    Pong:
      type: object
      description: A message and a timestamp.
      properties:
        message:
          type: string
        dateAndTime:
          type: string
          format: date-time
